
use_frameworks!

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

target 'OpenIMSDKiOS_Example' do
  pod 'OpenIMSDK', :path => '../'

  target 'OpenIMSDKiOS_Tests' do
    inherit! :search_paths

    
  end
end
