# fastlane add_plugin pgyer

lane :do_beta do |options|
    increment_build_number(
        build_number: Time.new.strftime("%Y%m%d%H%M"),
    )
    gym(
        scheme: "EEChat",
        export_method: "development",
        configuration: "Beta",
        output_directory: "./ipa/",
    )
    increment_build_number(
        build_number: "0",
    )
    upload_ipa()
end

def upload_ipa()
    api_key=ENV["pgyer_api_key"]
    user_key=ENV["pgyer_user_key"]
    pgyer(api_key: api_key, user_key: user_key)
end
