# fastlane add_plugin pgyer

lane :do_beta do |options|
    increment_build_number(
        build_number: Time.new.strftime("%Y%m%d%H%M"),
    )
    gym(
        scheme: "EEChat",
        export_method: "development",
        configuration: "Beta",
        output_directory: "./ipa/development/",
    )
    increment_build_number(
        build_number: "0",
    )
    upload_ipa()
end

def upload_ipa()
    api_key=ENV["pgyer_api_key"]
    user_key=ENV["pgyer_user_key"]
    pgyer(api_key: api_key, user_key: user_key)
end

lane :do_release do |options|
    increment_build_number(
        build_number: Time.new.strftime("%Y%m%d%H%M"),
    )
    gym(
        scheme: "EEChat",
        export_method: "app-store",
        configuration: "Release",
        output_directory: "./ipa/app-store/",
    )
    increment_build_number(
        build_number: "0",
    )

    upload_appstore()
end

def upload_appstore(ipa_path=Actions.lane_context[SharedValues::IPA_OUTPUT_PATH])
    script = %Q{
      APP_STORE_USERNAME=#{ENV["APP_STORE_USERNAME"]}
      APP_STORE_PASSWORD=#{ENV["APP_STORE_PASSWORD"]}
      
      IPA_PATH="#{ipa_path}"
      xcrun altool --upload-app --file "$IPA_PATH" --username "$APP_STORE_USERNAME" --password "$APP_STORE_PASSWORD"
    }
    sh(script)
  end